create table public.shared_side_dish_configs (
  id bigint generated by default as identity primary key,
  store_id bigint not null references public.stores(id) on delete cascade,
  effective_date date not null,
  items jsonb not null default '[]'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (store_id, effective_date)
);

create index shared_side_dish_configs_store_effective_date_idx
  on public.shared_side_dish_configs (store_id, effective_date desc);

alter table public.shared_side_dish_configs enable row level security;
revoke all privileges on public.shared_side_dish_configs from anon, authenticated;
grant select, insert, update, delete on public.shared_side_dish_configs to authenticated;

create policy "store users select own shared side dish configs" on public.shared_side_dish_configs for select to authenticated using (
  exists (select 1 from public.users where id = auth.uid() and role = 'store_user' and store_id = shared_side_dish_configs.store_id)
);
create policy "store users insert own shared side dish configs" on public.shared_side_dish_configs for insert to authenticated with check (
  exists (select 1 from public.users where id = auth.uid() and role = 'store_user' and store_id = shared_side_dish_configs.store_id)
);
create policy "store users update own shared side dish configs" on public.shared_side_dish_configs for update to authenticated using (
  exists (select 1 from public.users where id = auth.uid() and role = 'store_user' and store_id = shared_side_dish_configs.store_id)
) with check (
  exists (select 1 from public.users where id = auth.uid() and role = 'store_user' and store_id = shared_side_dish_configs.store_id)
);
create policy "store users delete own shared side dish configs" on public.shared_side_dish_configs for delete to authenticated using (
  exists (select 1 from public.users where id = auth.uid() and role = 'store_user' and store_id = shared_side_dish_configs.store_id)
);
